### ISSUE TITLE
Can this be done with traefik

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [stefanprodan/dockprom#156]
Can this setup be achieved with traefik rather than caddy? I tried to convert this to use traefik and IDK if it's my lack of experience or if it's possible since everything I google involving prometheus and traefik uses docker swarm or kubernetes.

**Comment by nightah** [comment]
I assume this link is also you: https://www.reddit.com/r/selfhosted/comments/curkjt/experience_using_dockernot_swarm_mode_with/

As per the comments there, it is completely possible to use whatever reverse proxy of your choice, be it nginx, traefik, caddy or otherwise.

Caddy was just the choice for this project and has stuck since, there's also nothing stopping you from reverse proxying the caddy instance with your traefik instance.
