### ISSUE TITLE
Monitor Traefik

### ISSUE THREAD

**Issue by joao-p-marques** [stefanprodan/dockprom#196]
Hi. This project is really god for setting up a monitoring system.

I was wondering if we could also use it to monitor Traefik, especially if it could replace Nginx and Caddy.

We could possibly integrate with https://doc.traefik.io/traefik/observability/metrics/prometheus/

**Comment by nightah** [comment]
You can replace Caddy with whatever you like, and if you prefer to put Traefik in the stack that is also possible.
I personally do not use Caddy at all and instead use my primary nginx instance.

The intent for Dockprom is to have a fully-integrated and working solution which is why it is set up the way it is.
