### ISSUE TITLE
Few ideas to add

### ISSUE THREAD

**Issue by JuezFenix** [stefanprodan/dockprom#211]
Hi, 

I think that add influxdb, telegraf and varken should be a very good idea because permit see a much more datas.

May be another optionaly adds are https://github.com/metalmatze/alertmanager-bot or https://github.com/MikeSafonov/prometheus-telegram-alert and https://github.com/prymitive/karma

**Comment by nightah** [comment]
There's nothing stopping users from adding Varken to their stacks, the intent specifically around dockprom is to provide users with some basic dashboards and a stack to provide monitoring/alerting.

Since Varken is quite specifically centered around specific applications and the applications other than karma are centered around telegram we wouldn't add them to the stack because it's not so much a one size fits all.

We look to cater to the lowest common denominator to ensure that the stack is lean and maintainable and so that elements that are introduced are likely to be utilised by many rather than the few.
