### ISSUE TITLE
How to include multiple container name in single expresion

### ISSUE THREAD

**Issue by rapkalya** [stefanprodan/dockprom#219]
as in alert rule you specified absent(container_memory_usage_bytes{name="jenkins"})  how to include multiple names in single expression so i don't repeat the step again for another container , is there any step where we can include all container in one expression like absent(container_memory_usage_bytes{name="jenkins", name="nginx", name="nginx2"}) to reduce line of code . if yes please provide sample code .TQ

**Comment by nightah** [comment]
I do not believe this is possible, you would need a rule for each container.

You could use a regex to match multiple containers like `absent(container_memory_usage_bytes{name=~"alerthub|authelia|jenkins"})` but this will not provide the intended result because the absent query will return false if any results are found.
