### ISSUE TITLE
nodeexporter permission denied

### ISSUE THREAD

**Issue by zavod** [stefanprodan/dockprom#29]
Got this error: 
> nodeexporter    | time="2017-10-12T07:19:45Z" level=error msg="Error on statfs() system call for \"/rootfs/var/lib/docker/containers/3ba4123c2ff67826a1869c0c3e2ac7e36beea1601b97ff3075e117448af39300/shm\": permission denied" source="filesystem_linux.go:57"

Is it ok?

**Comment by danielmenezesbr** [comment]
I got same error.

**Comment by davidterranova** [comment]
+1

**Comment by morgandenning** [comment]
getting this as well

**Comment by stefanprodan** [comment]
This could be related to the upgrade of Node Exporter v0.15 #26

Can you please rollback to the v0.14 and see if this still happens? This is the last commit before the upgrade https://github.com/stefanprodan/dockprom/commit/b2ded43c9d055d6573576ae080554a3c9faf8109

Thanks

**Comment by Viaguld** [comment]
Hello!
I`ve managed to solve this problem.
The cause is that starting from version 0.15 node-exporter drops its privilegies to user `nobody`.
Also from version 0.15 the container needs to be started in privileged mode so it can collect system clock statistics (adjtime stats).
If possible, I can do pull request or just paste yml config of node-exporter container

**Comment by stefanprodan** [comment]
@Viaguld do a PR please, thanks
