### ISSUE TITLE
understaing the meaning of cpu usage graph in grafana

### ISSUE THREAD

**Issue by carlosjpr-collab** [stefanprodan/dockprom#291]
Hi, 

I am inquiring about the meaning of the 2% container CPU usage metric.

 ![image](https://github.com/stefanprodan/dockprom/assets/38086105/24ecf8b1-a0d6-43d3-b778-93f26a4022a4)

Since I have 16 cores, does it imply that this container is utilizing 0.02 * 16 = 0.32 CPU? Is that correct? What about CPU load? Any information that could help us understand would be appreciated.

Thank you.

**Comment by patrickfenn** [comment]
Hi, I do not work on this project, but I do work on operating systems professionally, so I think I  can explain. The way these resource monitors work is that it scans the /proc/ fs, and takes a snapshot of resource usage. They can then calculate total load by taking the difference of system uptime and total cpu time. Since they do not have per core breakdown, it is possible that this is just a single core.

**Comment by nightah** [comment]
You can also get a good explanation of each query by toggling the `Explain` button and also looking at the definition of said metric (in this case [cAdvisor's `container_cpu_user_seconds_total`](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md#prometheus-container-metrics):

![image](https://github.com/stefanprodan/dockprom/assets/3339418/13f29669-93ec-4347-8022-af9c992c8980)
