### ISSUE TITLE
Docker Host: Network graph not updating

### ISSUE THREAD

**Issue by johnbritto1** [stefanprodan/dockprom#61]
Hello,
My Host: Ubuntu Mini 16.04 LTS x64 
The Network Usage graph of Host in grafana does not update. 
Tested by downloading a 1 GB file using wget in host. 

I thought of changing the ubuntu network interface naming from enp0s3 to eth0 on the host would work, but it didn't.  Any idea how to troubleshoot?

Thanks

**Comment by nightah** [comment]
That's because the nodeexporter container isn't set to use network_mode: host.
If you have a look at the additional file `docker-compose.exporters.yml` this includes the correct configuration to export network details from the Docker Host, keep in mind you'll need to change the Grafana query if you only want a specific interface.

**Comment by johnbritto1** [comment]
@nightah Thanks. The steps I taken to fix it.
1. Remove the prometheus and grafana container along with its volume.
2. Change the targets with <host IP>: port for cadvisor and nodeexporter in ~/dockprom/prometheus/prometheus.yml  file.
3. Change line 1155 as "expr": "irate(node_network_receive_bytes{device=\"eth0\"}[1m])",
    Change line 1163 as "expr": "irate(node_network_transmit_bytes{device=\"eth0\"}[1m])",
4. Run:   ADMIN_USER=admin ADMIN_PASSWORD=admin docker-compose up -d
5. Run:  docker-compose -f docker-compose.exporters.yml up -d
Which registered the cadvisor and nodeexporter to host network. 

and host network graph IN/OUT works.
