### ISSUE TITLE
Incorrect values for storage related graphs

### ISSUE THREAD

**Issue by uLan08** [stefanprodan/dockprom#64]
For Used Storage under Docker Containers dashboard I get
![screenshot from 2018-03-07 17-51-40](https://user-images.githubusercontent.com/14162336/37085593-68364bca-2230-11e8-988d-229edeaf2d3a.png)
Which is clearly not true because I only have a 500GB drive

Then for Free Storage under Docker Host dashboard, I am not sure what my `fstype` is, querying ` node_filesystem_free` on prometheus gave a lot of output. So I tried 
`aufs` which gave
![screenshot from 2018-03-07 17-51-55](https://user-images.githubusercontent.com/14162336/37085806-f614872c-2230-11e8-8a65-ea0296662b13.png)
and `ext4` which gave
![screenshot from 2018-03-07 17-58-07](https://user-images.githubusercontent.com/14162336/37085864-1ced9816-2231-11e8-92e3-d08defc48b2a.png)

which is still incorrect because `df -h` shows that I have 68G free.

**Comment by tmtben** [comment]
+1

I have the same issue using the default dockprom conf on Ubuntu Server 16.04 with Docker 18.03.0-ce and overlay2.

**Comment by nightah** [comment]
This is usually because you might have shared volumes mounted within multiple containers.
For example you might have `/mnt/bigfileshere` mounted on two different containers, so this effectively gets counted twice.

I would suggest you look at only including specific devices in your query, here's what I have for mine:
`sum(container_fs_usage_bytes{device="nerv/ROOT/arch"})`

Because all of my Docker configuration sits within that device it gives me an accurate representation, other volumes which might be mounted across multiple containers don't sit in that respective device.
