### ISSUE TITLE
grafana/dashboards/docker_container.json file can be used for k8s containers?

### ISSUE THREAD

**Issue by ramdhakne** [stefanprodan/dockprom#67]
I have defined datasource for my k8s containers in open shift and used the json file from your project
by changing datasource from "Prometheus" to "<my-datasource>". it seems to catch the graphs correctly but does not display any data.

Any idea?

Thanks,
Ram

**Comment by nightah** [comment]
I assume that's because when you change the data source it likely just inserts test walk data.
I suspect you could likely get it working on a k8s cluster but you likely would need to change some of the inputs and perhaps filter on your nodes/pods.

@stefanprodan any insight you might be able to provide? Would the swarmprom repo be a better alternative for this?
