### ISSUE TITLE
Use provisioning feature of grafana

### ISSUE THREAD

**Issue by pSchaub** [stefanprodan/dockprom#71]
Grafana supports provisioning to automate the process of adding Datasources & Dashboards.
We should use this feature instead of an own setup script.

See also this project: https://github.com/vegasbrianc/prometheus

**Comment by nightah** [comment]
I implemented this but removed it not long after because currently you don't have the ability to change and save a provisioned dashboard via the user interface.

You can see https://github.com/stefanprodan/dockprom/pull/105, when the referenced upstream issue has implemented a fix we will look to change this again.
